name: ci/cd Pipeline
on:
  push:
    branches: [main]
jobs:
  build:
    name: build and cache docker image 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: 123456
        options: >-
          --health-cmd="redis-cli -a 123456 ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --network-alias chat-redis
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and cache image (GHCR)
        uses: docker/build-push-action@v5
        id: docker_build_push
        with:
          context: .
          file: ./Dockerfile
          target: final
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-final:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-final:cache,mode=max
          tags: ghcr.io/${{ github.repository }}-final:latest
  deploy:
      name: Deploy to Server
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: SSH Deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              echo "Pulling latest Docker image..."
              cd chatPro
              docker-compose pull
              docker-compose up -d
